apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: NodePort
  ports:
    - name: auth
      port: 8096
      protocol: TCP
      targetPort: 8096
      nodePort: 31700
  selector:
    app: auth-service



